#!/bin/sh

set -e

INSTALL_ROOT="/cm/shared/apps/bcbio/$(date +%Y%m%d)-devel"

yum -y install git python-argparse
module load gcc/4.8.2
mkdir -p "$INSTALL_ROOT/"{tools,data}
wget https://raw.github.com/chapmanb/bcbio-nextgen/master/scripts/bcbio_nextgen_install.py
chmod 755 bcbio_nextgen_install.py
./bcbio_nextgen_install.py \
	"$INSTALL_ROOT/data" \
	--sudo --isolate \
	--tooldir "$INSTALL_ROOT/tools" \
	--genomes GRCh37 --aligners bwa --aligners bowtie2
