---
- name: install docker
  yum: name=docker-io state=latest

- name: add local docker group with consistent gid
  group: name=docker gid=10000

- name: use local docker group
  lineinfile:
    dest: /etc/sysconfig/docker
    regexp: ^other_args=
    line: other_args="-G docker"
  notify: restart docker

- name: start docker
  service: name=docker state=started
