---
- name: install collectl
  yum: name=collectl state=present

- name: run collectl
  service: name=collectl enabled=yes state=started

- name: install docker
  yum: name=docker-io state=present

- name: install mosh
  yum: name=mosh state=present

- name: install R
  yum: name=R state=present
