---
- name: install collectl
  yum: name=collectl state=present

- name: run collectl
  service: name=collectl enabled=yes state=started

- name: install mosh
  yum: name=mosh state=present

# R-java's package scripts (`rpm -q --scripts R-java`) sometimes hang in
# 'R CMD javareconf'. Kill it after a reasonable amount of time if it hasn't
# finished; the package remains cleanly installed since the package script
# ignores the return value.
- name: install R-java
  yum: name=R-java state=present
  async: 180
  poll: 5
  ignore_errors: yes

- name: Kill straggling R-java package script
  command: pkill Rcmd
  ignore_errors: yes

- name: install R
  yum: name=R state=present
