---
- name: update bios
  hosts: all
  sudo: true

  tasks:
    - name: create /root/firmware
      file: path=/root/firmware state=directory

    # http://www.dell.com/support/home/us/en/19/product-support/servicetag/DBNL212/drivers
    - name: copy m420 firmware
      when: "'{{ansible_product_name}}' == 'PowerEdge M420'"
      copy: src=/home/jwm/dell-firmware/m420/ dest=/root/firmware owner=root group=root mode=0755

    - name: update m420 bios
      when: "'{{ansible_product_name}}' == 'PowerEdge M420'"
      shell: "/root/firmware/BIOS_G9YW5_LN_2.3.3.BIN -q 2>&1 | grep -v ^prelink:"

    - name: update m420 esm
      when: "'{{ansible_product_name}}' == 'PowerEdge M420'"
      shell: "/root/firmware/ESM_Firmware_3F4WV_LN_1.66.65_A00.BIN -q 2>&1 | grep -v ^prelink:"

    - name: update m420 storage backplane
      when: "'{{ansible_product_name}}' == 'PowerEdge M420'"
      shell: "/root/firmware/Firmware_681JN_LN32_1.00_A00.BIN -q 2>&1 | grep -v ^prelink:"

    - name: update m420 lifecycle controller
      when: "'{{ansible_product_name}}' == 'PowerEdge M420'"
      shell: "/root/firmware/Lifecycle-Controller_Legacy_Application_TR4J7_LN_1.4.2.12_A00.BIN -q 2>&1 | grep -v ^prelink:"

    - name: update m420 cpld
      when: "'{{ansible_product_name}}' == 'PowerEdge M420'"
      shell: "/root/firmware/M420_CPLD_Firmware_NN0NN_LN_1.0.6.BIN -q 2>&1 | grep -v ^prelink:"

    - name: update m420 sas raid
      when: "'{{ansible_product_name}}' == 'PowerEdge M420'"
      shell: "/root/firmware/SAS-RAID_Firmware_32KD2_LN_20.13.0-0007_A08.BIN -q 2>&1 | grep -v ^prelink:"


    # http://www.dell.com/support/home/us/en/19/product-support/servicetag/HY4T212/drivers
    - name: copy r420 firmware
      when: "'{{ansible_product_name}}' == 'PowerEdge R420'"
      copy: src=/home/jwm/dell-firmware/r420/ dest=/root/firmware owner=root group=root mode=0755

    - name: update r420 bios
      when: "'{{ansible_product_name}}' == 'PowerEdge R420'"
      shell: "/root/firmware/BIOS_WV40N_LN_2.3.3.BIN -q 2>&1 | grep -v ^prelink:"

    - name: update r420 esm
      when: "'{{ansible_product_name}}' == 'PowerEdge R420'"
      shell: "/root/firmware/ESM_Firmware_XH6FX_LN_1.57.57_A00.BIN -q 2>&1 | grep -v ^prelink:"

    - name: update r420 storage backplane
      when: "'{{ansible_product_name}}' == 'PowerEdge R420'"
      shell: "/root/firmware/SAS-Non-RAID_Firmware_K161K_LN_07.03.06.00_A11.BIN -q 2>&1 | grep -v ^prelink:"

    - name: update r420 lifecycle controller
      when: "'{{ansible_product_name}}' == 'PowerEdge R420'"
      shell: "/root/firmware/Lifecycle-Controller_Application_C19M0_LN_1.4.2.12_A00.BIN -q 2>&1 | grep -v ^prelink:"

    - name: update r420 nic
      when: "'{{ansible_product_name}}' == 'PowerEdge R420'"
      shell: "/root/firmware/Network_Firmware_NF92Y_LN_7.10.18.BIN -q 2>&1 | grep -v ^prelink:"

    - name: update r420 sas raid
      when: "'{{ansible_product_name}}' == 'PowerEdge R420'"
      shell: "/root/firmware/SAS-RAID_Firmware_V8010_LN_21.3.0-0009_A05.BIN -q 2>&1 | grep -v ^prelink:"


    # http://www.dell.com/support/home/us/en/19/product-support/servicetag/4475322/drivers
    - name: copy r620 firmware
      when: "'{{ansible_product_name}}' == 'PowerEdge R620'"
      copy: src=/home/jwm/dell-firmware/r620/ dest=/root/firmware owner=root group=root mode=0755

    - name: update r620 bios
      when: "'{{ansible_product_name}}' == 'PowerEdge R620'"
      shell: "/root/firmware/BIOS_543GH_LN_2.4.3.BIN -q 2>&1 | grep -v ^prelink:"

    - name: update r620 esm
      when: "'{{ansible_product_name}}' == 'PowerEdge R620'"
      shell: "/root/firmware/ESM_Firmware_3F4WV_LN_1.66.65_A00.BIN -q 2>&1 | grep -v ^prelink:"

    - name: update r620 storage backplane
      when: "'{{ansible_product_name}}' == 'PowerEdge R620'"
      shell: "/root/firmware/Firmware_681JN_LN32_1.00_A00.BIN -q 2>&1 | grep -v ^prelink:"

    - name: update r620 lifecycle controller
      when: "'{{ansible_product_name}}' == 'PowerEdge R620'"
      shell: "/root/firmware/Lifecycle-Controller_Application_C19M0_LN_1.4.2.12_A00.BIN -q 2>&1 | grep -v ^prelink:"

    - name: update r620 sas non-raid
      when: "'{{ansible_product_name}}' == 'PowerEdge R620'"
      shell: "/root/firmware/SAS-Non-RAID_Firmware_K161K_LN_07.03.06.00_A11.BIN -q 2>&1 | grep -v ^prelink:"

    - name: update r620 sas raid
      when: "'{{ansible_product_name}}' == 'PowerEdge R620'"
      shell: "/root/firmware/SAS-RAID_Firmware_PYJ75_LN_21.3.0-0009_A05.BIN -q 2>&1 | grep -v ^prelink:"


    # http://www.dell.com/support/home/us/en/19/product-support/servicetag/4475322/drivers
    - name: copy r820 firmware
      when: "'{{ansible_product_name}}' == 'PowerEdge R820'"
      copy: src=/home/jwm/dell-firmware/r820/ dest=/root/firmware owner=root group=root mode=0755

    - name: update r820 bios
      when: "'{{ansible_product_name}}' == 'PowerEdge R820'"
      shell: "/root/firmware/R820_BIOS_NC1W7_LN_2.2.3.BIN -q 2>&1 | grep -v ^prelink:"

    - name: update r820 esm
      when: "'{{ansible_product_name}}' == 'PowerEdge R820'"
      shell: "/root/firmware/ESM_Firmware_3F4WV_LN_1.66.65_A00.BIN -q 2>&1 | grep -v ^prelink:"

    - name: update r820 nic
      when: "'{{ansible_product_name}}' == 'PowerEdge R820'"
      shell: "/root/firmware/Network_Firmware_NF92Y_LN_7.10.18.BIN -q 2>&1 | grep -v ^prelink:"

    - name: update r820 lifecycle controller
      when: "'{{ansible_product_name}}' == 'PowerEdge R820'"
      shell: "/root/firmware/Lifecycle-Controller_Application_C19M0_LN_1.4.2.12_A00.BIN -q 2>&1 | grep -v ^prelink:"

    - name: update r820 sas non-raid
      when: "'{{ansible_product_name}}' == 'PowerEdge R820'"
      shell: "/root/firmware/SAS-Non-RAID_Firmware_K161K_LN_07.03.06.00_A11.BIN -q 2>&1 | grep -v ^prelink:"

    - name: update r820 sas raid
      when: "'{{ansible_product_name}}' == 'PowerEdge R820'"
      shell: "/root/firmware/SAS-RAID_Firmware_PYJ75_LN_21.3.0-0009_A05.BIN -q 2>&1 | grep -v ^prelink:"
